### ISSUE TITLE
Node.js Package 

### ISSUE THREAD

**Issue by joramkimata** [Kalebu/mtaa#1]
Hello Kalebu!

I was wondering if i can create npm package (node.js version) inspired by you!

**Comment by Kalebu** [comment]
Hello @joramkimata 

I think that's a great idea, we need more of these for our developer communities 

Please let me know incase of anything that I would assist this 

Cheers 
Kalebu Jordan

**Comment by joramkimata** [comment]
Sure i will start work on it soon, i will add you as maintainer also

**Comment by Kalebu** [comment]
I will now close this issue
